name: Code Style

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '{{cookiecutter.module_name}}/locale/**'
      - '{{cookiecutter.module_name}}/static/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '{{cookiecutter.module_name}}/locale/**'
      - '{{cookiecutter.module_name}}/static/**'

jobs:
  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install gettext
        run: sudo apt install gettext
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version-file: ".github/workflows/python-version.txt"
          cache: "pip"
      - name: Install pretalx
        run: pip3 install pretalx
      - name: Install Dependencies
        run: pip3 install isort -Ue .
      - name: Run isort
        run: isort -c .
  flake:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install gettext
        run: sudo apt install gettext
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version-file: ".github/workflows/python-version.txt"
          cache: "pip"
      - name: Install pretalx
        run: pip3 install pretalx
      - name: Install Dependencies
        run: pip3 install flake8 flake8-bugbear -Ue .
      - name: Run flake8
        run: flake8 .
        working-directory: .
  black:
    name: black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install gettext
        run: sudo apt install gettext
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version-file: ".github/workflows/python-version.txt"
          cache: "pip"
      - name: Install pretalx
        run: pip3 install pretalx
      - name: Install Dependencies
        run: pip3 install black -Ue .
      - name: Run black
        run: black --check .
        working-directory: .
  djhtml:
    name: djhtml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install gettext
        run: sudo apt install gettext
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version-file: ".github/workflows/python-version.txt"
          cache: "pip"
      - name: Install pretalx
        run: pip3 install pretalx
      - name: Install Dependencies
        run: pip3 install djhtml -Ue .
  packaging:
    name: packaging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install gettext
        run: sudo apt install gettext
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version-file: ".github/workflows/python-version.txt"
          cache: "pip"
      - name: Install pretalx
        run: pip3 install pretalx
      - name: Install Dependencies
        run: pip3 install twine check-manifest -Ue .
      - name: Run check-manifest
        run: check-manifest .
        working-directory: .
      - name: Build package
        run: python setup.py sdist
        working-directory: .
      - name: Check package
        run: twine check dist/*
        working-directory: .
